name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm i
      - run: npm run build
