name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
        env:
          CI: false

      - run: npm i
      - run: npm run build

      - run: ls
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: build
          target: /var/www/dota_captains_mode
      - run: ls
